DROP INDEX "words_letter1_index";
DROP INDEX "words_letter2_index";
DROP INDEX "words_letter3_index";
DROP INDEX "words_letter4_index";
DROP INDEX "words_letter5_index";
DROP INDEX "words_letter6_index";
DROP INDEX "words_letter7_index";
DROP INDEX "words_letter8_index";
DROP INDEX "words_letter9_index";
DROP INDEX "words_letter10_index";
DROP INDEX "words_letter11_index";
DROP INDEX "words_letter12_index";
DROP INDEX "words_letter13_index";
DROP INDEX "words_letter14_index";
DROP INDEX "words_letter15_index";
DROP INDEX "words_letter16_index";
ALTER TABLE "words" drop column "length";
ALTER TABLE "words" drop column "letter1";
ALTER TABLE "words" DROP COLUMN "letter2";
ALTER TABLE "words" DROP COLUMN "letter3";
ALTER TABLE "words" DROP COLUMN "letter4";
ALTER TABLE "words" DROP COLUMN "letter5";
ALTER TABLE "words" DROP COLUMN "letter6";
ALTER TABLE "words" DROP COLUMN "letter7";
ALTER TABLE "words" DROP COLUMN "letter8";
ALTER TABLE "words" DROP COLUMN "letter9";
ALTER TABLE "words" DROP COLUMN "letter10";
ALTER TABLE "words" DROP COLUMN "letter11";
ALTER TABLE "words" DROP COLUMN "letter12";
ALTER TABLE "words" DROP COLUMN "letter13";
ALTER TABLE "words" DROP COLUMN "letter14";
ALTER TABLE "words" DROP COLUMN "letter15";
ALTER TABLE "words" DROP COLUMN "letter16";
ALTER TABLE "words" ADD COLUMN "length" integer GENERATED ALWAYS AS (LENGTH(IMMUTABLE_UNACCENT("words"."word"))) STORED NOT NULL;
ALTER TABLE "words" ADD COLUMN "letter1" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 1, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 1, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter2" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 2, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 2, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter3" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 3, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 3, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter4" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 4, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 4, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter5" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 5, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 5, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter6" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 6, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 6, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter7" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 7, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 7, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter8" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 8, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 8, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter9" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 9, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 9, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter10" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 10, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 10, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter11" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 11, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 11, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter12" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 12, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 12, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter13" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 13, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 13, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter14" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 14, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 14, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter15" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 15, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 15, 1))) ELSE NULL END) STORED;
ALTER TABLE "words" ADD COLUMN "letter16" varchar(1) GENERATED ALWAYS AS (CASE WHEN SUBSTRING("words"."word", 16, 1) IS NOT NULL THEN IMMUTABLE_UNACCENT(UPPER(SUBSTRING("words"."word", 16, 1))) ELSE NULL END) STORED;
CREATE INDEX "words_letter1_index" ON "words" USING btree ("letter1");
CREATE INDEX "words_letter2_index" ON "words" USING btree ("letter2");
CREATE INDEX "words_letter3_index" ON "words" USING btree ("letter3");
CREATE INDEX "words_letter4_index" ON "words" USING btree ("letter4");
CREATE INDEX "words_letter5_index" ON "words" USING btree ("letter5");
CREATE INDEX "words_letter6_index" ON "words" USING btree ("letter6");
CREATE INDEX "words_letter7_index" ON "words" USING btree ("letter7");
CREATE INDEX "words_letter8_index" ON "words" USING btree ("letter8");
CREATE INDEX "words_letter9_index" ON "words" USING btree ("letter9");
CREATE INDEX "words_letter10_index" ON "words" USING btree ("letter10");
CREATE INDEX "words_letter11_index" ON "words" USING btree ("letter11");
CREATE INDEX "words_letter12_index" ON "words" USING btree ("letter12");
CREATE INDEX "words_letter13_index" ON "words" USING btree ("letter13");
CREATE INDEX "words_letter14_index" ON "words" USING btree ("letter14");
CREATE INDEX "words_letter15_index" ON "words" USING btree ("letter15");
CREATE INDEX "words_letter16_index" ON "words" USING btree ("letter16");
